<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MATH3823 Generalized Linear Models - 6&nbsp; Loglinear models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./5_logisticmodel.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear models</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATH3823 Generalized Linear Models</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Weekly schedule</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0_preface.html" class="sidebar-item-text sidebar-link">Overview</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_linearmodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Essentials of Normal Linear Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_GLM-Theory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">GLM Theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_GLM-Fitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GLM Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_logisticmodel.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling proportions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_loglinearmodel.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear models</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="toc-section-number">6.1</span>  Overview</a></li>
  <li><a href="#motivating-examples" id="toc-motivating-examples" class="nav-link" data-scroll-target="#motivating-examples"><span class="toc-section-number">6.2</span>  Motivating examples</a>
  <ul class="collapse">
  <li><a href="#sec-melanoma" id="toc-sec-melanoma" class="nav-link" data-scroll-target="#sec-melanoma"><span class="toc-section-number">6.2.1</span>  Malignant melanoma</a></li>
  <li><a href="#flu-vaccine" id="toc-flu-vaccine" class="nav-link" data-scroll-target="#flu-vaccine"><span class="toc-section-number">6.2.2</span>  Flu vaccine</a></li>
  </ul></li>
  <li><a href="#maximum-likelihood-estimation" id="toc-maximum-likelihood-estimation" class="nav-link" data-scroll-target="#maximum-likelihood-estimation"><span class="toc-section-number">6.3</span>  Maximum likelihood estimation</a></li>
  <li><a href="#model-fitting-in-r" id="toc-model-fitting-in-r" class="nav-link" data-scroll-target="#model-fitting-in-r"><span class="toc-section-number">6.4</span>  Model fitting in <strong>R</strong></a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">6.5</span>  Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loglinear models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="overview" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">6.1</span> Overview</h2>
<p>In this chapter, we deal with data sets in which the response variable <span class="math inline">\(y\)</span> is a count and the explanatory variables are all factors – i.e. qualitative variables. Initially we assume <span class="math inline">\(y\)</span> has a Poisson distribution.</p>
<p>See Chapter 9 of Dobson and Barnett (2008). See also Agresti (1996) <em>An introduction to categorical data analysis</em>.</p>
<p>We assume a generalized linear model with</p>
<ul>
<li>responses (counts) having independent Poisson distributions;</li>
<li>a logarithmic link function (hence the name <em>log-linear model</em>).</li>
</ul>
<p>Consider, for example, the two-way contingency table in <a href="#tbl-twoway">Table&nbsp;<span>6.1</span></a>}:</p>
<div id="tbl-twoway" class="anchored">
<table class="table">
<caption>Table&nbsp;6.1: A two-way contingency table with <span class="math inline">\(k_1\)</span> rows and <span class="math inline">\(k_2\)</span> columns, where each entry <span class="math inline">\(y_{ij}\)</span> is a count.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;"><span class="math inline">\(\dots\)</span></th>
<th style="text-align: center;"><span class="math inline">\(j\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\dots\)</span></th>
<th style="text-align: center;"><span class="math inline">\(k_2\)</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(y_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1j}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1k_2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1+}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(i\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{i1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1j}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{ik_2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{i+}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(k_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{k_11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{k_12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1j}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{k_2k_2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1k_1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">\(y_{+1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{+2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{1j}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\dots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{+k_2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(y_{++}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>In row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span> of <a href="#tbl-twoway">Table&nbsp;<span>6.1</span></a>} we assume <span class="math display">\[
y_{ij} \sim \text{Po}(\lambda_{ij})
\]</span> where <span id="eq-2waymodel"><span class="math display">\[
\log \lambda_{ij} = \mu + \alpha_i + \beta_j + (\alpha \beta)_{ij}.
\tag{6.1}\]</span></span> Here <span class="math inline">\(\mu\)</span> is called the <em>main effect</em>; <span class="math inline">\(\alpha_i\)</span> is a <em>row effect</em>; <span class="math inline">\(\beta_j\)</span> is a <em>column effect</em>; and <span class="math inline">\((\alpha \beta)_{ij}\)</span> denotes an <em>interaction effect</em> parameter. Some or all of these effects must be present in the model, with constraints to ensure that the model is identifiable – this is sometimes refered ot as the <em>identifiability</em> or <em>aliasing problem</em>. Generally, <strong>R</strong> function automatically sets the first level of each effect to zero to achieve model identification. Thus, for the two-way model, <span class="math display">\[
\alpha_1 = 0, \quad \beta_1 = 0, \quad
(\alpha \beta)_{11}=(\alpha \beta)_{1j}=(\alpha \beta)_{k1}=0.
\]</span></p>
</section>
<section id="motivating-examples" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="motivating-examples"><span class="header-section-number">6.2</span> Motivating examples</h2>
<section id="sec-melanoma" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-melanoma"><span class="header-section-number">6.2.1</span> Malignant melanoma</h3>
<p>The data in <a href="#tbl-melanomacount1">Table&nbsp;<span>6.2</span></a> are from a study of 400 patients with malignant melanoma, a particular form of skin cancer (see Dobson and Barnett, p.172). For each tumour, its type and site were recorded. The data in <a href="#tbl-melanomacount1">Table&nbsp;<span>6.2</span></a> comprise the numbers of tumours <span class="math inline">\(y\)</span> in each combination of site and tumour-type. This is a two-way <em>contingency table</em>. We want to know how melanoma frequency depends on site and type.</p>
<div id="tbl-melanomacount1" class="anchored">
<table class="table">
<caption>Table&nbsp;6.2: Melanoma counts by type and site.</caption>
<thead>
<tr class="header">
<th>Type</th>
<th style="text-align: center;">Head</th>
<th style="text-align: center;">Trunk</th>
<th style="text-align: center;">Extremities</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hutchinson’s melanotic freckle</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">34</td>
</tr>
<tr class="even">
<td>Superficial spreading melanoma</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">115</td>
<td style="text-align: center;">185</td>
</tr>
<tr class="odd">
<td>Nodular</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">73</td>
<td style="text-align: center;">125</td>
</tr>
<tr class="even">
<td>Indeterminate</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">68</td>
<td style="text-align: center;">106</td>
<td style="text-align: center;">226</td>
<td style="text-align: center;">400</td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-melanomapercent1" class="anchored">
<table class="table">
<caption>Table&nbsp;6.3: Percentages across columns within rows for melanoma data.</caption>
<thead>
<tr class="header">
<th>Type</th>
<th style="text-align: center;">Head</th>
<th style="text-align: center;">Trunk</th>
<th style="text-align: center;">Extremities</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hutchinson’s melanotic freckle</td>
<td style="text-align: center;">64.7</td>
<td style="text-align: center;">5.9</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td>Superficial spreading melanoma</td>
<td style="text-align: center;">8.6</td>
<td style="text-align: center;">29.2</td>
<td style="text-align: center;">62.2</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="odd">
<td>Nodular</td>
<td style="text-align: center;">15.2</td>
<td style="text-align: center;">26.4</td>
<td style="text-align: center;">58.4</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td>Indeterminate</td>
<td style="text-align: center;">19.6</td>
<td style="text-align: center;">30.4</td>
<td style="text-align: center;">50.0</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">17.0</td>
<td style="text-align: center;">26.5</td>
<td style="text-align: center;">56.5</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-melanomapercent2" class="anchored">
<table class="table">
<caption>Table&nbsp;6.4: Percentages across rows within columns for melanoma data.</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th style="text-align: center;">Head</th>
<th style="text-align: center;">Trunk</th>
<th style="text-align: center;">Extremities</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hutchinson’s melanotic freckle</td>
<td style="text-align: center;">32.4</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">4.4</td>
<td style="text-align: center;">8.5</td>
</tr>
<tr class="even">
<td>Superficial spreading melanoma</td>
<td style="text-align: center;">23.5</td>
<td style="text-align: center;">50.9</td>
<td style="text-align: center;">50.9</td>
<td style="text-align: center;">46.3</td>
</tr>
<tr class="odd">
<td>Nodular</td>
<td style="text-align: center;">27.9</td>
<td style="text-align: center;">31.1</td>
<td style="text-align: center;">32.3</td>
<td style="text-align: center;">31.3</td>
</tr>
<tr class="even">
<td>Indeterminate</td>
<td style="text-align: center;">16.2</td>
<td style="text-align: center;">16.0</td>
<td style="text-align: center;">12.4</td>
<td style="text-align: center;">14.0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">100.0</td>
<td style="text-align: center;">99.9</td>
<td style="text-align: center;">100.0</td>
<td style="text-align: center;">100.0</td>
</tr>
</tbody>
</table>
</div>
<p>Although we have two factors, and , that we may use as predictors, standard ANOVA regression methods are inappropriate here as the dependent variable is not continuous but is instead a count. We will use <em>log-linear regression</em>, a type of generalized linear model, to analyse these data.</p>
<p><a href="#tbl-melanomapercent1">Table&nbsp;<span>6.3</span></a> shows row and <a href="#tbl-melanomapercent2">Table&nbsp;<span>6.4</span></a> column percentages for these data. For example, 15.2% of nodular melanomas occurred in the head and neck, 26.4% in the trunk, and 58.4% in the extremities. Compare this to the equivalent figures for Hutchinson’s melanotic freckles: 64.7%, 5.9%, and 29.4% - strikingly different. So different types of melanomas are more likely to occur in different locations.</p>
</section>
<section id="flu-vaccine" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="flu-vaccine"><span class="header-section-number">6.2.2</span> Flu vaccine</h3>
<p>The data in <a href="#tbl-flucount">Table&nbsp;<span>6.5</span></a> are from a randomized controlled trial in which 73 patients were randomized into two groups (see Dobson and Barnett, 2008, p.173). The treatment group was given a flu vaccine, while the control group was given a placebo.<br>
Levels of an antibody (HIA) were measured after 6 weeks and classified into three groups: Low, Moderate, and High.</p>
<div id="tbl-flucount" class="anchored">
<table class="table">
<caption>Table&nbsp;6.5: Antibody responses to flu vaccine from a randomized controlled trial.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Low</th>
<th style="text-align: center;">Moderate</th>
<th style="text-align: center;">High</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Placebo</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">Vaccine</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">16</td>
</tr>
</tbody>
</table>
</div>
<p>Is the pattern of response the same for each treatment group? The percentages in <a href="#tbl-flupercent1">Table&nbsp;<span>6.6</span></a> suggest not - row percentages indicate lower responses in the placebo group.</p>
<div id="tbl-flupercent1" class="anchored">
<table class="table">
<caption>Table&nbsp;6.6: Percentages across rows within columns for antibody responses to flu vaccine.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Low</th>
<th style="text-align: center;">Moderate</th>
<th style="text-align: center;">High</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Placebo</td>
<td style="text-align: center;">65.8</td>
<td style="text-align: center;">21.1</td>
<td style="text-align: center;">13.2</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td style="text-align: center;">Vaccine</td>
<td style="text-align: center;">17.1</td>
<td style="text-align: center;">51.4</td>
<td style="text-align: center;">31.4</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">42.4</td>
<td style="text-align: center;">35.6</td>
<td style="text-align: center;">22.0</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-flupercent2" class="anchored">
<table class="table">
<caption>Table&nbsp;6.7: Percentages across rows within columns for antibody responses to flu vaccine.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Low</th>
<th style="text-align: center;">Moderate</th>
<th style="text-align: center;">High</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Placebo</td>
<td style="text-align: center;">80.6</td>
<td style="text-align: center;">30.8</td>
<td style="text-align: center;">31.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">Vaccine</td>
<td style="text-align: center;">19.4</td>
<td style="text-align: center;">69.2</td>
<td style="text-align: center;">68.8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="maximum-likelihood-estimation" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="maximum-likelihood-estimation"><span class="header-section-number">6.3</span> Maximum likelihood estimation</h2>
<p>Recall that for each cell <span class="math inline">\(Y_{ij} \sim \text{Po}(\lambda_{ij})\)</span> so <span class="math inline">\(\mbox{E}[Y_{ij}]= \lambda_{ij}\)</span>. However, we estimate <span class="math inline">\(\hat{\lambda}_{ij} = y_{ij}\)</span> only for the <em>saturated model</em> given by <a href="#eq-2waymodel">Equation&nbsp;<span>6.1</span></a>. In general, for non-saturated models, the estimate <span class="math inline">\(\hat\lambda_{ij} \ne y_{ij}\)</span>.</p>
<p>Consider the independence model for a 2-way table, that is where <span class="math inline">\((\alpha \beta)_{ij} = 0\)</span> for all <span class="math inline">\(i,j\)</span>. Here, <span id="eq-loglinear"><span class="math display">\[
\log \lambda_{ij} = \mu +\alpha_i + \beta_j \tag{6.2}\]</span></span> and <span class="math inline">\(y_{ij}\)</span> is the observed count for cell <span class="math inline">\((i,j)\)</span>, so the likelihood is given by <span class="math display">\[
L(\lambda; y)
=  \prod_{i,j} \frac{e^{-\lambda_{ij}} \lambda_{ij}^{y_{ij}}}{y_{ij}!}
\]</span> and the log-likelihood is <span class="math display">\[
l(\lambda; y)
=  \sum_{i,j} \left\{ y_{ij} \log \lambda_{ij} - \lambda_{ij} -
    \log y_{ij}!\right\}.
\]</span> Next, using <a href="#eq-loglinear">Equation&nbsp;<span>6.2</span></a>, gives <span class="math display">\[
l(\lambda; y) =  \sum_{i,j} \left\{ y_{ij} (\mu + \alpha_i + \beta_j)
    - \exp(\mu + \alpha_i + \beta_j)  - \log y_{ij}! \right\}
\]</span> which can be re-written as <span id="eq-twowayloglik"><span class="math display">\[
l(\lambda; y)   =  \mu y_{++} + \sum_i \alpha_i y_{i+} + \sum_j \beta_j y_{+ j}
    - e^{\mu} \left(\sum_i e^{\alpha_i}\right) \left(\sum_j e^{\beta_j}
    \right) - \sum_{ij} \log y_{ij}!.
\tag{6.3}\]</span></span></p>
<p>The maximum likelihood estimates of the model parameters are obtained in the usual way. Differentiating <a href="#eq-twowayloglik">Equation&nbsp;<span>6.3</span></a> with respect to <span class="math inline">\(\mu\)</span> and setting the result to zero gives, at the MLE, <span class="math display">\[
y_{++} = e^{\hat{\mu}} \left(\sum_i e^{\hat{\alpha}_i}\right)
\left(\sum_j e^{\hat{\beta}_j}\right).
\]</span></p>
<p>Differentiating <a href="#eq-twowayloglik">Equation&nbsp;<span>6.3</span></a> with respect to <span class="math inline">\(\alpha_i\)</span> (where <span class="math inline">\(i \ne 1\)</span> because <span class="math inline">\(\alpha_1=0\)</span> to avoid an identifiability problem) and setting the result to zero gives, at the MLE, <span class="math display">\[
y_{i+} = e^{\widehat{\mu}}  e^{\widehat{\alpha}_i} \left(\sum_j e^{\widehat{\beta}_j}\right).  \notag \\
% = \sum_j \widehat{\lambda_{ij}} = \widehat{\lambda}_{i+} ~~~~(i \not= 1).
\]</span> Differentiating <a href="#eq-twowayloglik">Equation&nbsp;<span>6.3</span></a> with respect to <span class="math inline">\(\beta_j\)</span> (where <span class="math inline">\(j \not= 1\)</span> because <span class="math inline">\(\beta_1=0\)</span>) and setting the result to zero gives, at the MLE, <span class="math display">\[
y_{+j} = e^{\widehat{\mu}}  e^{\widehat{\beta}_j} \left(\sum_i e^{\widehat{\alpha}_i}\right).
\]</span> Then <span id="eq-two-way.mle"><span class="math display">\[
\frac{y_{i+}\ y_{+j}}{y_{++}} = e^{\widehat{\mu}+\widehat{\alpha}_i+\widehat{\beta}_j}  
= \widehat{\lambda}_{ij}.  
\tag{6.4}\]</span></span> It follows that <span class="math display">\[
\widehat{\lambda}_{i+} = y_{i+} \quad
\widehat{\lambda}_{+j} = y_{+j} \quad  
\widehat{\lambda}_{++} = y_{++}.  
\]</span></p>
<p>Thus, the total fitted count in row <span class="math inline">\(i\)</span> is identical to the total observed count in row <span class="math inline">\(i\)</span>. Further, the total fitted count in column <span class="math inline">\(j\)</span> is equal to the total observed count in column <span class="math inline">\(j\)</span> and the total fitted count equals the total observed count.</p>
</section>
<section id="model-fitting-in-r" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="model-fitting-in-r"><span class="header-section-number">6.4</span> Model fitting in <strong>R</strong></h2>
<p>Consider an analysis of Melanoma data introduced in <a href="#sec-melanoma"><span>Section&nbsp;6.2.1</span></a>.</p>
<p>To test the independence of <span class="math inline">\(\texttt{Type}\)</span> and <span class="math inline">\(\texttt{Size}\)</span>, we fit the model <span class="math display">\[
\text{Count} \sim \text{Type} + \text{Site}
\]</span> assuming Poisson counts and a logarithmic link function, using the commands:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>melanoma <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">"data/melanoma.txt"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(melanoma)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>type.F <span class="ot">=</span> <span class="fu">as.factor</span>(type)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>site.F <span class="ot">=</span> <span class="fu">as.factor</span>(site)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>glm1 <span class="ot">=</span> <span class="fu">glm</span>(count <span class="sc">~</span> type.F <span class="sc">+</span> site.F, <span class="at">family=</span><span class="st">'poisson'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = count ~ type.F + site.F, family = "poisson")

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-3.0453  -1.0741   0.1297   0.5857   5.1354  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.7544     0.2040   8.600  &lt; 2e-16 ***
type.F2       1.6940     0.1866   9.079  &lt; 2e-16 ***
type.F3       1.3020     0.1934   6.731 1.68e-11 ***
type.F4       0.4990     0.2174   2.295  0.02173 *  
site.F2       0.4439     0.1554   2.857  0.00427 ** 
site.F3       1.2010     0.1383   8.683  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 295.203  on 11  degrees of freedom
Residual deviance:  51.795  on  6  degrees of freedom
AIC: 122.91

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>We see that the residual deviance for this model is <span class="math inline">\(51.795\)</span> on <span class="math inline">\(6\)</span> degrees of freedom. If the model is true, the residual deviance will have an approximate <span class="math inline">\(\chi^2\)</span> distribution on <span class="math inline">\(6\)</span> degrees of freedom. If the model is not true, the residual deviance will probably be too large to correspond to this distribution. Thus we calculate the <span class="math inline">\(p\)</span>-value in the upper tail of the <span class="math inline">\(\chi^2_6\)</span> distribution, which can be computed using the command:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">51.795</span>,<span class="dv">6</span>,<span class="at">lower.tail=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.050465e-09</code></pre>
</div>
</div>
<p>This strongly indicates that the independence model is inadequate. Therefore, unless we can spot alternative simplifications, we will have to use the saturated model.</p>
<p>We can look at residuals from the model see where the departures from independence occur. The largest residual is for Hutchinson’s freckle on the head and neck, which occurs more often than would be expected under independence.</p>
<p>For the saturated model, <span class="math inline">\(\widehat{\lambda}_{ij} = y_{ij}\)</span>. In this example, <span class="math inline">\(\sum_{ij} \widehat{\lambda}_{ij} = \sum_{ij} y_{ij} = 400\)</span>, so the probability of a tumour being in category <span class="math inline">\((i,j)\)</span> is <span class="math inline">\(y_{ij}/400\)</span> — just the observed proportions.</p>
<p>Note that in <a href="#tbl-melanomacount1">Table&nbsp;<span>6.2</span></a> we have a total of <span class="math inline">\(y_{++} = 400\)</span> observations. If the data were truly Poisson, this would be a suspiciously round number. In reality, this total was fixed by design, so we should take into account the fact that <span class="math inline">\(y_{++} = 400\)</span> and fit a more suitable model, such as the <em>multinomial</em> model which we will meet in the next chapter.</p>
</section>
<section id="exercises" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">6.5</span> Exercises</h2>
<p><strong>Exercises to be added later.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./5_logisticmodel.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelling proportions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>