---
title: "MATH3823 - Solution to Chapter 6 Exercises (Draft: 25/05/2023)"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  markdown: 
    wrap: 72
---

------------------------------------------------------------------------

::: callout-important
#### Using R Markdown files

If you are reading this online, on the module website, then this is
output from an [R Markdown](http://rmarkdown.rstudio.com) Notebook. At
the top-righthand corner of the page under $\texttt{Code}$, select
$\texttt{Download Rmd}$ to download the original R Markdown notebook --
this is recommended so that you can edit and re-run code within the
notebook. When you run code within the notebook, the results appear
beneath the code. If you do download the notebook, then try executing a
chunk by clicking the *Run* button within the chunk or by placing your
cursor inside it and pressing *Ctrl+Shift+Enter*.
:::

------------------------------------------------------------------------

#### Exercise 6.1

a.  If $Y \sim P(\lambda)$, then
    $E(Y) = \lambda,\ \mbox{var}(Y) = \lambda, \ E(Y^2) = \lambda + \lambda^2$.
    Hence for the mixture model \begin{align*}
       E(Y) &= E(Y|X=1)P(X=1) + E(Y|X=2)P(X=2) = \frac{1}{2}(\lambda_1+\lambda_2)\\
       E(Y^2) &= E(Y^2|X=1)P(X=1) + E(Y^2|X=2)P(X=2) = \frac{1}{2}
    (\lambda_1+\lambda_1^2+\lambda_2+\lambda_2^2),
     \end{align*} so that $$
    \mbox{Var}(Y) = \frac{1}{2} (\lambda_1 + \lambda_1^2 + \lambda_2 + \lambda_2^2) - \left\{\frac{1}{2}(\lambda_1 + \lambda_2)\right\}^2
       = \lambda + (\lambda_1 - \lambda_2)^2/4.
    $$

b.  Writing
    $\overline{Y} = \frac{1}{2} (\overline{Y}_1 + \overline{Y}_2)$,
    where $\overline{Y}_j$ has mean $\lambda_j$ and variance
    $\lambda_j/30$, $j=1,2$, we see that \begin{equation*}
      E[(\overline{Y})^2] = \frac{1}{4} E\left[ (\overline{Y}_1)^2 + 2\overline{Y}_1\overline{Y}_2  + (\overline{Y}_2)^2\right] 
      = \frac{1}{4} \{\lambda_1^2 + \lambda_1/30 + 2 \lambda_1 \lambda_2 + \lambda_2^2\ + \lambda_2/30\}.
    \end{equation*} Also \begin{equation*}
      E[\sum_{i=1}^{60} Y_i^2]  = E[\sum_{i=1}^{30} Y_i^2] + E[ \sum_{i=31}^{60} Y_i^2] = 30(\lambda_1^2 + \lambda_1 + \lambda_2^2 + \lambda_2).
    \end{equation*} Hence $$
      E(S^2) = \frac{1}{59} E\left[\sum_{i=1}^{60} Y_i^2 - 60 (\overline{Y})^2\right]
       = \frac{1}{2} (\lambda_1 + \lambda_2) + \frac{60}{4 \cdot 59} (\lambda_1-\lambda_2)^2,
    $$ which is larger than $\lambda$ when $\lambda_1 \neq \lambda_2$.

    The $\chi^2$ goodness of fit statistic is just \begin{equation*}
    X^2 = \sum_k (O_k-E_k)^2/E_k = (n-1) S^2/\overline{Y},
    \end{equation*} in terms of observed values $O_i = Y_i$ and expected
    values $E_i = \overline{Y}$. Here $n=60$. Under the null Poisson
    model, the numerator and denominator have the same expectation and
    for large n, $X^2 \sim \chi^2_{n-1}$ approximately. Under the
    mixture model the numerator has a larger expectation and $X^2$ will
    be larger in distribution than $\chi^2_{n-1}$.

c.  When a scale parameter $\phi$ is present, it can be used to
    represent the true scale variability in the model, plus the effects
    of overdispersion.

\

#### Exercise 6.2


**I Percentages adding to 100% across housing**

**Low Contact:**

| Satisfaction | Low | Medium | High |
|:------------:|:---:|:------:|:----:|
| Tower blocks | 25    | 30       | 37     |
|  Apartments  | 50    | 43       | 41     |
|    Houses    | 26    | 27       | 23     |
|    Total     | 100    | 100       | 100     |

**High Contact:**

| Satisfaction | Low | Medium | High |
|:------------:|:---:|:------:|:----:|
| Tower blocks | 11    | 48       | 25     |
|  Apartments  | 46    | 43       | 48     |
|    Houses    | 43    | 39       | 26     |
|    Total     | 100    | 100       | 100     |



**II Percentages adding to 100\% across satisfaction**

**Low Contact:**

| Satisfaction | Low | Medium | High | Total |
|:------------:|:---:|:------:|:----:|:----:|
| Tower blocks | 30    | 25       | 46     | 100 |
|  Apartments  | 41    | 24       | 35     | 100 |
|    Houses    | 38    | 27       | 35     | 100 |

**High Contact:**

| Satisfaction | Low | Medium | High | Total |
|:------------:|:---:|:------:|:----:|:----:|
| Tower blocks | 19    | 26       | 55     | 100 |
|  Apartments  | 31    | 26       | 43     | 100 |
|    Houses    | 38    | 31       | 31     | 100 |


**III Percentages adding to 100\% across contact**

**Low Satisfaction:**

| Contact | Low   | High | Total |
|:------------:|:-----:|:----:|:----:|
| Tower blocks | 66    |  34  | 100 |
|  Apartments  | 48    |  52  | 100 |
|    Houses    | 34    |  66  | 100 |

**Medium Satisfaction:**

| Contact | Low   | High | Total |
|:------------:|:-----:|:----:|:----:|
| Tower blocks | 53    |  47  | 100 |
|  Apartments  | 40    |  60  | 100 |
|    Houses    | 31    |  69  | 100 |


**High Satisfaction:**

| Contact | Low   | High | Total |
|:------------:|:-----:|:----:|:----:|
| Tower blocks | 50    |  50  | 100 |
|  Apartments  | 37    |  63  | 100 |
|    Houses    | 37    |  63  | 100 |


The three tables  give percentages adding to 100 over housing, satisfaction and contact, respectively. 


The $R$ output shows the result of fitting a model with all 3 *first-order* interactions (also known as *two-way* interactions) but no *second-order* interaction (*three-way* interaction). The deviance $6.89 \sim \chi^2_4$ is not significant, so there is no need to consider the saturated model. The residuals all lie between $\pm 2$, again indicating the model is an adequate fit. There are strongly significant coefficients within each
first-order interaction; hence, further simplification has not been attempted. For this dataset it does not seem reasonable to condition on any of the marginal totals so the counts are assumed to arise from a Poisson model, not a product-multinomial model.

```{r}
count = c(65,54,100,34,47,100,130,76,111,141,116,191,67,48,62,130,105,104)

sat=rep(1:3,6)
housing = rep(1:3,rep(6,3))
contact=rep(rep(1:2,rep(3,2)),3)

# Convert into factors
sat = as.factor(sat)
housing = as.factor(housing)
contact = as.factor(contact)

## Modelling
glm1 = glm(count ~ sat+housing+contact+
             sat:housing+housing:contact+sat:contact, 
           poisson)
summary(glm1)


residuals(glm1, type="pearson")
```

Since there is no second-order interaction, the log odds ratios for any two variables are constant given the third. Here are some
interpretations based on the tables of percentages and the coefficients in the $R$ output.

-    For each level of contact, Tables I and II show that the ratio of high to low satisfaction is higher for tower block residents than for apartment dwellers, which is in turn higher than for house residents. This interpretation is confirmed by the coefficients $\texttt{sat3.housing2} = -0.64$ and $\texttt{sat3.housing3} = -0.95$.

-    For each level of satisfaction, Tables I and III show that contact with neighbours increases as one moves from housing category tower block to apartment to house. This interpretation is confirmed by the coefficients $\texttt{housing2.contact2} = 0.57$ and $\texttt{housing3.contact2} = 0.89$.

-  For each level of housing, Tables II and III show that high
satisfaction goes with high contact. This interpretation is
confirmed in particular by the coefficient $\texttt{sat3.contact2} = 0.33$.

For me the overall conclusions are partly expected and partly unexpected. I am surprised that tower blocks have a higher satisfaction than houses, and that house residents have greater contact than tower block residents. But it is natural that higher satisfaction is associated with higher contact.

\
